"""app/plugins/ — Sakura 原生插件系统。"""

from app.plugins.base import PluginBase, PluginContext
from app.plugins.capabilities import PluginCapabilities, PluginCapabilityRegistry
from app.plugins.discovery import PluginDiscovery
from app.plugins.events import PluginEventBus, ScopedEventBus
from app.plugins.manager import PluginLoadResult, PluginManager
from app.llm.prompts.types import ContextFragment, ContextRequest
from app.plugins.models import (
    KNOWN_PLUGIN_PERMISSIONS,
    PERMISSION_CHAT_UI,
    PERMISSION_CONTEXT_PROVIDER,
    PERMISSION_EVENT_APP,
    PERMISSION_EVENT_CHARACTER,
    PERMISSION_EVENT_MESSAGE,
    PERMISSION_EVENT_TTS,
    PERMISSION_PLUGIN_SETTINGS,
    PERMISSION_PROMPT_PATCH,
    PERMISSION_RENDERER,
    PERMISSION_MOBILE_CHAT,
    PERMISSION_TOOL,
    PERMISSION_TOOLS_TAB,
    PLUGIN_API_VERSION,
    SUPPORTED_API_VERSIONS,
    ChatUIWidgetContribution,
    ContextProviderContribution,
    PluginEvent,
    PluginManifest,
    PluginManifestView,
    PluginSettingsAction,
    PluginSettingsContribution,
    PluginSettingsField,
    PluginSpec,
    PromptPatchContribution,
    RendererContribution,
    RendererCreateContext,
    ToolContribution,
    ToolsTabContribution,
)
from app.plugins.services import (
    PluginAgentService,
    PluginInputService,
    PluginMobileService,
    PluginServices,
    PluginTTSService,
    PluginUIService,
)

__all__ = [
    "ChatUIWidgetContribution",
    "ContextFragment",
    "ContextProviderContribution",
    "ContextRequest",
    "KNOWN_PLUGIN_PERMISSIONS",
    "PERMISSION_CHAT_UI",
    "PERMISSION_CONTEXT_PROVIDER",
    "PERMISSION_EVENT_APP",
    "PERMISSION_EVENT_CHARACTER",
    "PERMISSION_EVENT_MESSAGE",
    "PERMISSION_EVENT_TTS",
    "PERMISSION_PLUGIN_SETTINGS",
    "PERMISSION_PROMPT_PATCH",
    "PERMISSION_RENDERER",
    "PERMISSION_MOBILE_CHAT",
    "PERMISSION_TOOL",
    "PERMISSION_TOOLS_TAB",
    "PLUGIN_API_VERSION",
    "SUPPORTED_API_VERSIONS",
    "PluginAgentService",
    "PluginBase",
    "PluginCapabilities",
    "PluginCapabilityRegistry",
    "PluginContext",
    "PluginDiscovery",
    "PluginEvent",
    "PluginEventBus",
    "PluginInputService",
    "PluginMobileService",
    "PluginLoadResult",
    "PluginManager",
    "PluginManifest",
    "PluginManifestView",
    "PluginSettingsAction",
    "PluginSettingsContribution",
    "PluginSettingsField",
    "PluginServices",
    "PluginSpec",
    "PluginTTSService",
    "PluginUIService",
    "PromptPatchContribution",
    "RendererContribution",
    "RendererCreateContext",
    "ScopedEventBus",
    "ToolContribution",
    "ToolsTabContribution",
]
