"""app/config/defaults.py — 配置默认值。

所有配置项的默认值集中管理，供：
- 空配置时生成默认配置
- 配置迁移
- 测试
"""

from __future__ import annotations

# ---- API 默认值 ----
DEFAULT_BASE_URL = ""
DEFAULT_MODEL = ""
DEFAULT_API_TIMEOUT_SECONDS = 60

# ---- API 配置文件默认值 ----
DEFAULT_PROFILE_ID = "default"
DEFAULT_PROFILE_ALIAS = "默认"
DEFAULT_VISION_MODEL = ""
DEFAULT_TEXT_MODEL = ""

# ---- TTS 默认值 ----
DEFAULT_TTS_ENABLED = False
DEFAULT_TTS_PROVIDER = "none"
DEFAULT_GPT_SOVITS_API_URL = "http://127.0.0.1:9880/tts"
DEFAULT_GPT_SOVITS_REF_LANG = "ja"
DEFAULT_GPT_SOVITS_TEXT_LANG = "ja"
DEFAULT_GPT_SOVITS_TIMEOUT_SECONDS = 60

# ---- 主动屏幕感知默认值 ----
DEFAULT_SCREEN_AWARENESS_ENABLED = True
DEFAULT_SCREEN_AWARENESS_SCREEN_CONTEXT_ENABLED = True
DEFAULT_SCREEN_AWARENESS_CHECK_INTERVAL_MINUTES = 20
DEFAULT_SCREEN_AWARENESS_COOLDOWN_MINUTES = 10
DEFAULT_SCREEN_AWARENESS_SCREEN_CONTEXT_BATCH_LIMIT = 6

# ---- 记忆整理默认值 ----
DEFAULT_MEMORY_CURATION_ENABLED = True
DEFAULT_MEMORY_CURATION_TRIGGER_TURNS = 8
DEFAULT_MEMORY_CURATION_BACKFILL_LIMIT = 200

# ---- MCP 默认值 ----
DEFAULT_WINDOWS_MCP_ENABLED = False

# ---- 调试默认值 ----
DEFAULT_DEBUG_ENABLED = True
DEFAULT_DEBUG_BODY_ENABLED = False

# ---- UI 默认值 ----
DEFAULT_SUBTITLE_LANGUAGE = "zh"
DEFAULT_PORTRAIT_SCALE_PERCENT = 100
DEFAULT_PORTRAIT_SCALE_MIN = 50
DEFAULT_PORTRAIT_SCALE_MAX = 150
DEFAULT_FREE_ACCESS_ENABLED = True

# ---- 字体大小默认值 ----
# 单位：px
DEFAULT_SPEECH_FONT_SIZE = 19
SPEECH_FONT_SIZE_MIN = 10
SPEECH_FONT_SIZE_MAX = 24

DEFAULT_NAME_FONT_SIZE = 13
NAME_FONT_SIZE_MIN = 10
NAME_FONT_SIZE_MAX = 20

DEFAULT_INPUT_FONT_SIZE = 15
INPUT_FONT_SIZE_MIN = 12
INPUT_FONT_SIZE_MAX = 20

DEFAULT_BUTTON_FONT_SIZE = 15
BUTTON_FONT_SIZE_MIN = 12
BUTTON_FONT_SIZE_MAX = 20

# ---- 角色默认值 ----
DEFAULT_CHARACTER_ID = "sakura"
